name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  spec:
    name: Spec (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Download source
        uses: actions/checkout@v4

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Install shards
        run: shards install --skip-postinstall --skip-executables

      - name: Run specs
        run: crystal spec

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v4

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Check formatting
        run: crystal tool format --check

  ameba:
    name: Ameba
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Download source
        uses: actions/checkout@v4

      - name: Run Ameba linter
        uses: crystal-ameba/github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
